apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: flux-demo-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: flux-demo
  filterTags:
    pattern: '^v(?P<version>\d+\.\d+\.\d+)$'
    extract: '$version'
  policy:
    semver:
      range: ">=0.0.0"
