apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - service-nodeport-patch.yaml
images:
  - name: ghcr.io/cjfochler/flux-demo
    newTag: latest
