apiVersion: v1
kind: Service
metadata:
  name: flux-demo
  labels:
    app.kubernetes.io/name: flux-demo
spec:
  selector:
    app.kubernetes.io/name: flux-demo
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
  type: NodePort
