apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-demo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/apps/flux-demo/local
  prune: true
  wait: true
  timeout: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
